样本程序：

Reference: https://www.quantstart.com/articles/Jacobi-Method-in-Python-and-NumPy/

In [7]:
from pprint import pprint
from numpy import array, zeros, diag, diagflat, dot


def jacobi(A, b, N=25, x=None):                                                                                                                                                          
    if x is None:
        x = zeros(len(A[0]))

    # Create a vector of the diagonal elements of A                                                                                                                                                
    # and subtract them from A                                                                                                                                                                     
    D = diag(A)
    R = A - diagflat(D)
    # Iterate for N times                                                                                                                                                                          
    for i in range(N):
        x = (b - dot(R,x)) / D
    return x


def test_jacobi():
    A = array([[2.0,1.0],[5.0,7.0]])
    b = array([11.0,13.0])
    guess = array([1.0,1.0])

    sol = jacobi(A,b,N=25,x=guess)

    print('A:'); pprint(A)
    
    print("b:"); pprint(b)

    print("x:"); pprint(sol)

In [8]:
if __name__ == '__main__':
    test_jacobi()

A:
array([[2., 1.],
       [5., 7.]])
b:
array([11., 13.])
x:
array([ 7.11110202, -3.22220342])


--------

个人程序（算法不同，增加了计算循环次数）

In [1]:
def jacobi(A, b, x_init, epsilon = 1e-10, max_iterations = 10000):
    D = np.diag(np.diag(A))
    LU = A - D
    x = x_init
    for i in range(max_iterations):
        D_inv = np.diag(1/np.diag(D))
        x_new = np.dot(D_inv, b - np.dot(LU, x))
        if np.linalg.norm(x_new - x) < epsilon:
            break
        x = x_new
    return x_new, i