# Individual Assignment

### Problem 1
#### Question (a)
 

In [2]:
matrix_list=[[1,2,3],[4,5,6],[7,8,9]]
matrix_1=[matrix_list[i][-1] for i in range (3)]
print(matrix_1)

[3, 6, 9]


#### Question(b)

In [3]:
matrix_2=[2 * matrix_list[i][1] ** 2 for i in range (3)] 
print(matrix_2)

[8, 50, 128]


### Problem 2
#### Question (a)

In [4]:
import numpy as np

x = np.ones((8,8))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


#### Question (b)

In [6]:
y = np.ones((8,8))
y[::2,1::2] = 0
y[1::2,::2] = 0
print(y)


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


#### Question (c)

In [7]:
c = np.arange(2,50,5)
c[c%3!=0] = -c[c%3!=0]
print(c)

[ -2  -7  12 -17 -22  27 -32 -37  42 -47]


#### Question (d)

In [8]:
total = {'x' : x,'y' : y,'c' : c}
np.set_printoptions(precision=2)
for i, k in total.items():
    print(f'''matrix name is : {i}\n
    size:\t{k.size}\n
    shape:\t{k.shape}\n
    mean:\t{k.mean(0)}\n
    std:\t{k.std(0)}\n''')

matrix name is : x

    size:	64

    shape:	(8, 8)

    mean:	[1.   0.25 0.25 0.25 0.25 0.25 0.25 1.  ]

    std:	[0.   0.43 0.43 0.43 0.43 0.43 0.43 0.  ]

matrix name is : y

    size:	64

    shape:	(8, 8)

    mean:	[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]

    std:	[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]

matrix name is : c

    size:	10

    shape:	(10,)

    mean:	-8.3

    std:	27.158976416647224



### Problem 3
#### Question (a)

In [9]:
import math as mt
a = [3, 4, 5, 100, 10000, 1000000]
print('n\tp\t\t\t' + 'n p')
for j in range(3):
    p_1 = a[j] * mt.sqrt((0.25 + 0.25 - 2 * 0.5 * 0.5 * mt.cos(2 * mt.pi / a[j])))
    p_2 = a[3 + j] * mt.sqrt((0.25 + 0.25 - 2 * 0.5 * 0.5 * mt.cos(2 * mt.pi / a[3+j])))
    print('{:}\t{:.11f}'.format(a[j],p_1) + '{:>12} {:<.11f}'.format(a[j + 3],p_2))


n	p			n p
3	2.59807621135         100 3.14107590781
4	2.82842712475       10000 3.14159260224
5	2.93892626146     1000000 3.14159277010
