In [7]:
import sys
import matplotlib.pyplot as plt
import numpy as np
import math
import scipy.linalg

<font size = 3 color = black face = "Times New Roman">Problem 1

$x_{n + 1} = g(x_n)$  
$g(x) = {{1}\over{2}}(x + {{a^2}\over{x}})$  
$x_{n+1} = {{1}\over{2}}(x_n+{{a^2}\over{x_n}})\geq{a}$  
<font size = 3 color = black face = "Times New Roman">so no matter what ${x_1}$ we choose, $x_2, x_3$... must be larger than $a$  
$g^{'}(x) = {{1}\over{2}}(1 - {{a^2}\over{x^2}})$   
<font size = 3 color = black face = "Times New Roman">so if $x_n>a$, we can deduce that $g^{'}(x_n)<{{1}\over{2}}$ and $a<x_{n+1}<x_n$  
${x_{n+1}-x^*}\over{x_n-x^*}$ $=$ ${g'({\xi_n})(x_n-x^*)}\over{x_n-x^*} $$= g'({\xi_n})$  
<font size = 3 color = black face = "Times New Roman">easy to get ${x_{n}-x^*} < ({{1}\over{2}})^{n-2}(x_2-x^*)$  
$\lim_\limits{n\to \infty}{x_{n}-x^*} = 0$  
$\lim_\limits{n\to \infty}x_n = x^* = a$  
until now, we have proved that $x_n$ must converge to $a$

<font size = 3 color = black face = "Times New Roman">now let's prove the convergence is quadratic  
${g'({x^*}) = g'(a) = {{1}\over{2}}(a - a) = 0 } $  
$g''(x) = {{a^2}\over{x^3}}$ and $g''(x^*) = {{1}\over{a}} \neq 0$  
$\lim_\limits{n\to \infty}{{x_{n+1}-x^*}\over{{(x_n-x^*)}^2}}$ $=$ ${g''(x*)}\over{2!}$$ = $${1}\over{2a}$  
so the convergence is quadratic 

<font size = 3 color = black face = "Times New Roman">Problem 6

<font size = 3 color = black face = "Times New Roman">Introduction

<font size = 3 color = black face = "Times New Roman">In this problem, we will use LU and Cholesky method to solve Ax = b, and we will use several inner functions provided by scipy and numpy to help us solve this problem. Before that, I will explain the function.

<font size = 3 color = black face = "Times New Roman">scipy.linalg.lu_factor() will give us two matrix lu and piv.  
lu contains $U$ in its upper triangle, and $L$ in its lower triangle. The unit diagonal elements of $L$ are not stored.  
piv: pivot indices representing the permutation matrix $P$: row $i$ of matrix was interchanged with row $piv[i]$.  
when we use scipy.linalg.lu_solve(), both lu and piv are used, and this function will return us the solution $x$.

<font size = 3 color = black face = "Times New Roman">np.linalg.cholesky() will return us a matrix $L$, so we just need to solve to function $Ly = b$ and $L^Tx = y$, here we use scipy.linalg.solve() twice to solve this two function. 

In [21]:
n = 3  # use n = 3 as an example, but in fact our program can solve other n values
A = np.ones((n,n))
for i in range(n):
    for j in range(n):
        if i == j:
            A[i][j] = i+1
# construct matrix A
b = np.zeros((n,1))
for i in range(n):
    for j in range(n):
        b[i] = b[i] + A[i][j] * (j + 1)
#construct b
A, b

(array([[1., 1., 1.],
        [1., 2., 1.],
        [1., 1., 3.]]),
 array([[ 6.],
        [ 8.],
        [12.]]))

In [18]:
lu, piv = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve((lu,piv), b)
x

array([[1.],
       [2.],
       [3.],
       [4.]])

In [25]:
L = np.linalg.cholesky(A)
y = scipy.linalg.solve(L, b)
x = scipy.linalg.solve(L.T, y)
x

array([[1.],
       [2.],
       [3.]])