In [1]:
import numpy as np

### Problem 3

In [2]:
# Import the initial data.
x_k = np.array([1, 2, 3, 4, 6])
f_k = np.array([0.69, 1.10, 1.39, 1.61, 1.95])

In [3]:
# Construct the divided differences table.
n = len(f_k)
table = np.zeros((n,n))
table[0] = f_k
table = table.T
for k in range(1,n):
    for i in range(k,n):
        table[i][k] = (table[i][k-1] - table[i-1][k-1])/(x_k[i] - x_k[i-k])
table = np.around(table, decimals= 8)
print(f'The divided difference table is:')
print(f'  f_k\t\t1st\t\t2nd\t\t3rd\t\t4th\n{table}')

The divided difference table is:
  f_k		1st		2nd		3rd		4th
[[ 6.900000e-01  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00]
 [ 1.100000e+00  4.100000e-01  0.000000e+00  0.000000e+00  0.000000e+00]
 [ 1.390000e+00  2.900000e-01 -6.000000e-02  0.000000e+00  0.000000e+00]
 [ 1.610000e+00  2.200000e-01 -3.500000e-02  8.333330e-03  0.000000e+00]
 [ 1.950000e+00  1.700000e-01 -1.666667e-02  4.583330e-03 -7.500000e-04]]


In [4]:
# determine the coefficients of Newton polynomials
a = f_k.copy()
for i in range(n):
    a[i] = table[i][i]

In [5]:
def newton_eval(a, xData, x):
    # determine the interpolation value at x
    m = len(xData)
    n = m - 1
    p = a[n]
    for k in range(1,m):
        p = a[n-k] + (x - xData[n-k])*p
    return p

In [6]:
#interpolate at x = 2.4 and 4.2
x_1 = 2.4
f_1 = newton_eval(a, x_k, x_1)
x_2 = 4.2
f_2 = newton_eval(a, x_k, x_2)
print(f'When x = {x_1}, newton interpolating get {f_1}')
print(f'When x = {x_2}, newton interpolating get {f_2}')

When x = 2.4, newton interpolating get 1.2271968011199998
When x = 4.2, newton interpolating get 1.6487327718399998


### Problem 5

In [7]:
# Import the initial data.
alpha_data = np.array([0,5,10,15,20,25])
I_data = np.array([1.57080,1.57379,1.58284,1.59814,1.62003,1.64900])

#### Question 1

<font size = 3 color = black face = "Times New Roman">Uing Newton interpolating polynomial to get the soulution.

In [8]:
def newton_coeff(xData, yData):
    # determine the coefficients of Newton polynomials
    a = yData.copy()
    m = len(xData)
    for k in range(1,m):  # m=n+1: number of data points
        for i in range(k,m):
            a[i] = (a[i] - a[k-1])/(xData[i] - xData[k-1])
    return a

def newton_eval(a,xData, x):
    # determine the interpolation value at x
    m = len(xData)
    n = m - 1
    p = a[n]
    for k in range(1,m):
        p = a[n-k] + (x - xData[n-k])*p
    return p

In [9]:
a =  newton_coeff(alpha_data, I_data)
alpha = 2
I = newton_eval(a,alpha_data,alpha)
print(f'When Alpha = 2, I = {I} ')

When Alpha = 2, I = 1.57127472 


#### Question 2

In [10]:
# Define theoretical values and allowable errors
I_0 = 1.58
eps = 10 ** (-8)

<font size = 3 color = black face = "Times New Roman">First we do some easy tests.

In [11]:
print(newton_eval(a,alpha_data,8.5))
print(newton_eval(a,alpha_data,9))

1.579480295625
1.58053824


<font size = 3 color = black face = "Times New Roman">Hence we know that the right value should locate in range(8.5,9).

In [12]:
test_value = np.arange(8.5,9,0.000001)
for i in test_value:
    if abs(newton_eval(a,alpha_data,i)-I_0) < eps:
        print(f'When Alpha = {i}, I = 1.58')
        break
    else:
        continue

When Alpha = 8.74926399981345, I = 1.58
