Reference:   
1. https://en.wikipedia.org/wiki/Gauss%E2%80%93Seidel_method
2. https://www.quantstart.com/articles/Jacobi-Method-in-Python-and-NumPy/

In [3]:
from pprint import pprint
from numpy import array, zeros, zeros_like, dot, allclose

def gauss_seidel(A, b, N=25, x=None):
    """Solves the equation Ax=b via the Jacobi iterative method."""
    # Create an initial guess if needed                                                                                                                                                            
    if x is None:
        x = zeros_like(b)

    # Iterate for N times  
    for it_count in range(N):
        x_new = zeros_like(x)
        print("Iteration {0}: {1}".format(it_count, x))
        for i in range(A.shape[0]):
            s1 = dot(A[i, :i], x_new[:i])
            s2 = dot(A[i, i + 1:], x[i + 1:])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]
        if allclose(x, x_new, rtol=1e-8):
            break
        x = x_new
    return x

def test_gauss_seidel():
    A = array([[2.0,1.0],[5.0,7.0]])
    b = array([11.0,13.0])
    guess = array([1.0,1.0])

    sol = gauss_seidel(A,b,N=25,x=guess)

    print('A:'); pprint(A)
    
    print("b:"); pprint(b)

    print("x:"); pprint(sol)

In [4]:
if __name__ == '__main__':
    test_gauss_seidel()

Iteration 0: [1. 1.]
Iteration 1: [ 5.         -1.71428571]
Iteration 2: [ 6.35714286 -2.68367347]
Iteration 3: [ 6.84183673 -3.02988338]
Iteration 4: [ 7.01494169 -3.15352978]
Iteration 5: [ 7.07676489 -3.19768921]
Iteration 6: [ 7.0988446  -3.21346043]
Iteration 7: [ 7.10673022 -3.21909301]
Iteration 8: [ 7.10954651 -3.22110465]
Iteration 9: [ 7.11055232 -3.22182309]
Iteration 10: [ 7.11091154 -3.22207967]
Iteration 11: [ 7.11103984 -3.22217131]
Iteration 12: [ 7.11108566 -3.22220404]
Iteration 13: [ 7.11110202 -3.22221573]
Iteration 14: [ 7.11110786 -3.2222199 ]
Iteration 15: [ 7.11110995 -3.22222139]
Iteration 16: [ 7.1111107  -3.22222193]
Iteration 17: [ 7.11111096 -3.22222212]
Iteration 18: [ 7.11111106 -3.22222218]
A:
array([[2., 1.],
       [5., 7.]])
b:
array([11., 13.])
x:
array([ 7.11111106, -3.22222218])
